 const router= require('express').Router()
 const regc=  require('../controllers/regcontroller')
    const bannerc= require('../controllers/bannercontroller')
    const coursec=  require('../controllers/coursecontroller')
    const skillc= require('../controllers/skillcontroller')
     const resumec=  require('../controllers/resumecontroller')
     const eductionc=  require('../controllers/eductioncontroller')
    const queryc=   require('../controllers/querycontroller')
    const addressc = require('../controllers/addresscontroller')
   const handlelogin= require('../helpers/handlelogin')
   const upload=  require('../helpers/multer')
  

 router.get('/',regc.loginpage)
 router.post('/',regc.logincheck)
 router.get('/dashboard',handlelogin,regc.dashboard)
 router.get('/logout',handlelogin,regc.logout)
 router.get('/banner',handlelogin,bannerc.bannerpage)
router.get('/bannerupdateform/:id',handlelogin,bannerc.bannerform)
router.post('/bannerupdateform/:id', upload.single('img'),bannerc.bannerupdate)
router.get('/course',handlelogin,coursec.coursepage)
router.get('/addcourse',handlelogin,coursec.courseform)
router.post('/addcourse',upload.single('icon'),coursec.addcourse)
router.get('/deletestatus/:id',handlelogin,coursec.deletestatus)
router.get('/coursestatusupdate/:id',handlelogin,coursec.coursestatusupdate)
router.post('/course',handlelogin,coursec.search)
router.get('/skill',handlelogin,skillc.skillpage)
router.get('/addskill',handlelogin,skillc.addskillform)
router.post('/addskill',handlelogin,skillc.addskill)
router.get('/skilldelete/:id',handlelogin,skillc.skilldelete)
router.get('/skillstatusupdate/:id',handlelogin,skillc.statusupdate)
router.post('/skill',handlelogin,skillc.search)
router.get('/resume',  handlelogin, resumec.resumepage)
router.get('/resumeupdateform/:id',handlelogin,resumec.resumeupdateform)
router.post('/resumeupdateform/:id',handlelogin,resumec.resumeupdate)
router.get('/eduction',handlelogin,eductionc.eductionpage)
router.get('/courseadd',handlelogin,eductionc.eductionadd)
router.post('/courseadd',eductionc.updateeduction)
router.get('/deletecourtse/:id',handlelogin,eductionc.coursedelete)
router.get('/eductionstatusupdate/:id',handlelogin,eductionc.coursestatusupdate)
router.post('/eduction',eductionc.search)
router.get('/query',handlelogin,queryc.querypage)
router.get('/queryreply/:id',handlelogin,queryc.emailpage)
router.post('/queryreply/:id',upload.single('attachement'),queryc.sendmail)
router.get('/deleteemail/:id',handlelogin,queryc.emaildelete)
router.get('/address',handlelogin,addressc.addpage)
router.get('/addupdate/:id',handlelogin,addressc.update)
router.post('/addupdate/:id',addressc.formupdate)


 module.exports=router